name: Tests
on:
  push:
    branches:
      - alpha
  pull_request:
    branches:
      - alpha

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --frozen-lockfile
      - run: yarn test
